; -----------------------------------------------------
; Default processing for main views
; -----------------------------------------------------
HIDR_AUDTREETYPE=main_index
HIDR_AUDCHARTTYPE=main_index
HIDR_AUDDATATYPE=main_index
HIDR_AUDDRIVETYPE=main_index
HIDR_AUDENCLTYPE=main_index
HIDR_AUDGENTYPE=main_index
HIDR_AUDNETTYPE=main_index
HIDR_AUDROOMTYPE=main_index
HIDR_AUDTESTYPE=main_index

; -----------------------------------------------------

; -----------------------------------------------------
;		Dialogs
; -----------------------------------------------------
; -----------------------------------------------------
;		Menus
; -----------------------------------------------------
