//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Audtest.RC
//
#define IDC_CHART                       3
#define IDAPPLY                         3
#define CG_IDS_PHYSICAL_MEM             105
#define CG_IDS_DISK_SPACE               106
#define CG_IDS_DISK_SPACE_UNAVAIL       107
#define IDR_MAINFRAME                   128
#define CG_IDD_BASE                     204
#define IDB_BANDPASS                    1000
#define IDB_BANDPASS1                   1001
#define IDC_MOREINPUT                   1001
#define IDB_BANDSTOP                    1002
#define IDC_MOREOUTPUT                  1002
#define IDB_BANDSTOP1                   1003
#define IDB_BITMAP1                     1004
#define IDB_DRAGCURSORS                 1005
#define IDC_TXTINPUT                    1005
#define IDB_HIGHPASS                    1006
#define IDC_TXTOUTPUT                   1006
#define IDB_HIGHPASS1                   1007
#define IDC_TXTDUPLEX                   1007
#define IDB_LOWPASS                     1008
#define IDC_TXTSUMMARY                  1008
#define IDB_LOWPASS1                    1009
#define IDB_SPLASH256                   1011
#define IDC_STEREO                      1011
#define IDB_TREELIST                    1012
#define IDC_VERSION                     1012
#define IDB_TREELIST1                   1013
#define IDC_FORMATS                     1013
#define IDC_PREVIOUS                    1014
#define IDC_NEXT                        1015
#define IDC_MFRID                       1016
#define IDB_WIZ_BRD_END                 1017
#define IDC_PRODID                      1017
#define IDB_XVHIGH3                     1018
#define IDC_AUDCHKNAME                  1018
#define IDB_XVHIGH4                     1019
#define IDC_DEVID                       1019
#define IDC_SPECIAL                     1020
#define IDC_ADDDATA                     2001
#define IDC_ADDNEW                      2002
#define IDC_ALIGNMENT                   2003
#define IDC_AMP                         2004
#define IDC_AMP1                        2005
#define IDC_AMP2                        2006
#define IDC_AMP3                        2007
#define IDC_AMP4                        2008
#define IDC_AMP5                        2009
#define IDC_AUTOBND                     2012
#define IDC_AUTOCHART                   2013
#define IDC_AUTOINCREMENT               2014
#define IDC_AUTOINCREMENT2              2015
#define IDC_AUTOTIC                     2016
#define IDC_BMAJOR                      2017
#define IDC_BMAX                        2018
#define IDC_BMINOR                      2020
#define IDC_BROWSE                      2021
#define IDC_BROWSECHAN                  2022
#define IDC_BROWSEMIC                   2024
#define IDC_BROWSETARGET                2025
#define IDC_BROWSEAMP                   2025
#define IDC_BROWSEWAVE                  2026
#define IDC_BUDDY1                      2027
#define IDC_BUDDY2                      2028
#define IDC_CALIB                       2031
#define IDC_CALIBTYPE                   2032
#define IDC_CALNAME                     2033
#define IDC_CENTERFREQ                  2034
#define IDC_CHANNELDIFF                 2035
#define IDC_CLEAR                       2036
#define IDC_COLOR                       2037
#define IDC_COLOR2                      2038
#define IDC_COMBTYPE                    2039
#define IDC_COMPARE                     2040
#define IDC_COMPLIST                    2041
#define IDC_COMPNAME                    2042
#define IDC_COMPONENT                   2044
#define IDC_COMPTYPE                    2045
#define IDC_COMPUNIT                    2047
#define IDC_CONTINUOUS                  2048
#define IDC_RESSUFFIX                   2048
#define IDC_CORRELSIZE                  2049
#define IDC_CREATED                     2050
#define IDC_CURMAX                      2051
#define IDC_CURMIN                      2052
#define IDC_CVALUE                      2053
#define IDC_DATA                        2054
#define IDC_DATALIST                    2055
#define IDC_DATANAME                    2056
#define IDC_DATE                        2057
#define IDC_DATE2                       2058
#define IDC_DB                          2059
#define IDC_DCRES                       2060
#define IDC_DCRESIST                    2061
#define IDC_DESCRIPT                    2062
#define IDC_DEST                        2063
#define IDC_DIAMETER                    2064
#define IDC_DIGITS                      2065
#define IDC_DISK_SPACE                  2066
#define IDC_RESTYPE                     2066
#define IDC_DOCHART                     2067
#define IDC_DOIMPEDANCE                 2068
#define IDC_DOLOG                       2069
#define IDC_DOM                         2070
#define IDC_DOREPONSE                   2071
#define IDC_DRIVER                      2072
#define IDC_DRVRGROUP                   2073
#define IDC_PORT                        2073
#define IDC_DURATION                    2074
#define IDC_DUTYCYCLE                   2075
#define IDC_EDITED                      2077
#define IDC_DELTA                       2078
#define IDC_EMPHASIS                    2080
#define IDC_END                         2081
#define IDC_EXEINPLACE                  2082
#define IDC_TOTALTIME                   2082
#define IDC_EXEINPLACE2                 2083
#define IDC_NUMSAMPLES                  2083
#define IDC_F3                          2084
#define IDC_FACTOR                      2085
#define IDC_FEND                        2086
#define IDC_FFTWINDOW                   2087
#define IDC_FONTNAME                    2088
#define IDC_FRAME                       2089
#define IDC_FREEAIR                     2090
#define IDC_FREQ                        2091
#define IDC_FREQ1                       2092
#define IDC_TIME                        2092
#define IDC_GATED                       2092
#define IDC_FREQ2                       2093
#define IDC_FREQ3                       2094
#define IDC_FREQ4                       2095
#define IDC_FREQ5                       2096
#define IDC_FREQ30                      2097
#define IDC_FREQ60                      2098
#define IDC_FREQALL                     2099
#define IDC_FREQMARKER                  2100
#define IDC_FS                          2101
#define IDC_FSHAPE                      2102
#define IDC_L1                          2102
#define IDC_LEVEL                       2102
#define IDC_FSTART                      2103
#define IDC_R1                          2103
#define IDC_ENDFREQ                     2103
#define IDC_FTYPE                       2104
#define IDC_GENERIC1                    2105
#define IDC_GENERIC2                    2106
#define IDC_GENERIC3                    2107
#define IDC_GENERIC4                    2108
#define IDC_GENERIC5                    2109
#define IDC_GENERIC6                    2110
#define IDC_GENERIC7                    2111
#define IDC_GENERIC8                    2112
#define IDC_GENERIC9                    2113
#define IDC_GENERIC10                   2114
#define IDC_GENERIC11                   2115
#define IDC_GENERIC12                   2116
#define IDC_GENERIC13                   2117
#define IDC_GTITLE                      2118
#define IDC_GENERIC14                   2118
#define IDC_HIGHLOW                     2119
#define IDC_HITDRIVER                   2120
#define IDC_HITFREE                     2121
#define IDC_HITNONE                     2121
#define IDC_HITFREQ                     2122
#define IDC_HITNOMIC                    2122
#define IDC_HITFREQ30                   2123
#define IDC_HITNOAMP                    2123
#define IDC_HITFREQ60                   2124
#define IDC_HITIMP                      2125
#define IDC_HITNEAR                     2126
#define IDC_HITPULSE                    2127
#define IDC_HITSEAL                     2128
#define IDC_HORZ1                       2129
#define IDC_DELIMP                      2129
#define IDC_HORZ2                       2130
#define IDC_DELFREQ                     2130
#define IDC_HORZ3                       2131
#define IDC_DELFREQ30                   2131
#define IDC_IMAGE                       2132
#define IDC_DELFREE                     2132
#define IDC_IMAGINARY                   2133
#define IDC_DELPULSE                    2133
#define IDC_IMPEDANCE                   2134
#define IDC_INHERIT                     2135
#define IDC_DELNEAR                     2135
#define IDC_INPUTCAP                    2136
#define IDC_DELFREQ60                   2136
#define IDC_INPUTRES                    2137
#define IDC_DELSEAL                     2137
#define IDC_INVDATA                     2138
#define IDC_HITMASS                     2138
#define IDC_INVPHASE                    2139
#define IDC_DELMASS                     2139
#define IDC_ISLOG                       2140
#define IDC_HITGATE                     2140
#define IDC_ISRECT                      2141
#define IDC_DELGATE                     2141
#define IDC_LASTDATE                    2142
#define IDC_LASTEDIT                    2143
#define IDC_DELPORT                     2143
#define IDC_LAYOUT                      2144
#define IDC_LE                          2145
#define IDC_LEFTBROWSE                  2146
#define IDC_LEFTRESP                    2147
#define IDC_LINESTYLE                   2148
#define IDC_LINESTYLE2                  2149
#define IDC_LINEWEIGHT                  2150
#define IDC_LINEWEIGHT2                 2151
#define IDC_LIST1                       2152
#define IDC_LOCLIST                     2153
#define IDC_LOCLIST1                    2154
#define IDC_LOCLIST2                    2155
#define IDC_LOCLIST3                    2156
#define IDC_LOG                         2157
#define IDC_LOCLIST4                    2157
#define IDC_LVALUE                      2158
#define IDC_MAJOR                       2159
#define IDC_MARKHIGH                    2160
#define IDC_MARKLOW                     2161
#define IDC_MAX                         2162
#define IDC_SAMPLE                      2162
#define IDC_METHOD                      2163
#define IDC_MICBROWSE                   2164
#define IDC_MICRESP                     2165
#define IDC_MICRESPONSE                 2166
#define IDC_MICSENSE                    2167
#define IDC_AMPRESPONSE                 2167
#define IDC_MIN                         2168
#define IDC_MINOR                       2169
#define IDC_MOVER                       2170
#define IDC_NAME                        2171
#define IDC_NEARFREQ                    2172
#define IDC_NEGATIVE                    2173
#define IDC_NODE1                       2174
#define IDC_NODE2                       2175
#define IDC_NODROP                      2176
#define IDC_NOOUTPUT                    2177
#define IDC_NPOINTS                     2181
#define IDC_OCTAVE                      2182
#define IDC_OFFSET                      2183
#define IDC_REFERENCE                   2183
#define IDC_OHMS1                       2184
#define IDC_OHMS2                       2185
#define IDC_ONEPOWER                    2186
#define IDC_ONEFREQ                     2187
#define IDC_OPERATION                   2188
#define IDC_ORDER                       2189
#define IDC_OTHER                       2190
#define IDC_OUTOFPHASE                  2191
#define IDC_OUTPUT                      2193
#define IDC_OVALUE                      2194
#define IDC_PDIAM                       2195
#define IDC_PHASE                       2196
#define IDC_PHEIGHT                     2197
#define IDC_PHYSICAL_MEM                2198
#define IDC_PLAYTIME                    2200
#define IDC_PLENGTH                     2201
#define IDC_PLENGTH2                    2202
#define IDC_POINTER                     2203
#define IDC_POINTER_COPY                2204
#define IDC_PORTUNIT                    2205
#define IDC_PORTUNIT2                   2206
#define IDC_PORTUNIT3                   2207
#define IDC_POWER1                      2210
#define IDC_POWER2                      2211
#define IDC_PRADIUS                     2212
#define IDC_PREEMPHASIS                 2213
#define IDC_PROPERTIES                  2214
#define IDC_PULSERES                    2215
#define IDC_PWIDTH                      2216
#define IDC_Q                           2217
#define IDC_QA                          2218
#define IDC_QES                         2219
#define IDC_QL                          2220
#define IDC_QMS                         2221
#define IDC_QP                          2222
#define IDC_QTS                         2223
#define IDC_RADDB                       2224
#define IDC_RADFACTOR                   2225
#define IDC_RADIO1                      2226
#define IDC_RADIO2                      2227
#define IDC_RADIO3                      2228
#define IDC_RADMAX                      2229
#define IDC_RADMAXLIM                   2230
#define IDC_RADMIN                      2231
#define IDC_RADMINLIM                   2232
#define IDC_RATE                        2233
#define IDC_RE                          2234
#define IDC_REAL                        2235
#define IDC_RECORDTIME                  2238
#define IDC_REFERNAME                   2239
#define IDC_REMOVE                      2240
#define IDC_RESISTOR                    2241
#define IDC_REVERSE                     2242
#define IDC_RIGHTBROWSE                 2243
#define IDC_RIGHTRESP                   2244
#define IDC_RIPPLE                      2245
#define IDC_RSMOOTH1                    2246
#define IDC_RSMOOTH2                    2247
#define IDC_RSMOOTH3                    2248
#define IDC_RSMOOTH4                    2249
#define IDC_RSMOOTH5                    2250
#define IDC_RSMOOTH6                    2251
#define IDC_RSMOOTH7                    2252
#define IDC_RSMOOTH8                    2253
#define IDC_RVALUE                      2254
#define IDC_RSMOOTH9                    2254
#define IDC_SAMPLERATE                  2255
#define IDC_SAMPLESIZE                  2256
#define IDC_SCRL1                       2257
#define IDC_SCRL2                       2258
#define IDC_SCRL3                       2259
#define IDC_SCRL4                       2260
#define IDC_SCRL5                       2261
#define IDC_SCRL6                       2262
#define IDC_SCRL7                       2263
#define IDC_SCRL8                       2264
#define IDC_SEALED                      2265
#define IDC_SELAXISSCALE                2266
#define IDC_ADDMASS                     2266
#define IDC_SELAXISTITLE                2267
#define IDC_SELDATA                     2268
#define IDC_SELDRIVER                   2269
#define IDC_SELFONT                     2270
#define IDC_SELLABEL                    2271
#define IDC_SELLEGEND                   2272
#define IDC_SELREFER                    2273
#define IDC_SELSUBTITLE                 2274
#define IDC_SELTITLE                    2275
#define IDC_SELTITLEFONT                2276
#define IDC_SERIESRES                   2277
#define IDC_SHOWAXISSCALE               2278
#define IDC_SHOWAXISTITLE               2279
#define IDC_SHOWDATA                    2280
#define IDC_SHOWFREQ                    2281
#define IDC_SHOWGRID                    2282
#define IDC_SHOWLEGEND                  2283
#define IDC_SHOWPHASE                   2284
#define IDC_SHOWRATE                    2285
#define IDC_SHOWSIZE                    2286
#define IDC_SHOWSUBTITLE                2287
#define IDC_SHOWTIC                     2289
#define IDC_SHOWTITLE                   2290
#define IDC_SMALLCROSS                  2292
#define IDC_SMOOTH                      2293
#define IDC_SOURCE                      2294
#define IDC_SPIN1                       2297
#define IDC_SPIN2                       2298
#define IDC_SPIN3                       2299
#define IDC_SPIN8                       2300
#define IDC_SPIN4                       2301
#define IDC_SPIN5                       2302
#define IDC_SPIN7                       2303
#define IDC_SPIN6                       2304
#define IDC_SPINFREQ1                   2306
#define IDC_SPINFREQ2                   2307
#define IDC_SPINFREQ3                   2308
#define IDC_SPINMAJOR                   2309
#define IDC_SPINMAX                     2310
#define IDC_SPINMIN                     2311
#define IDC_SPINMINOR                   2313
#define IDC_SPINORDER                   2314
#define IDC_SPINVOLUME                  2315
#define IDC_SPLIT                       2316
#define IDC_CROSSPLUS                   2317
#define IDC_START                       2318
#define IDC_SWPLINEAR                   2320
#define IDC_SWPLOG                      2321
#define IDC_SWPSTEPS                    2322
#define IDC_TARGET                      2323
#define IDC_TESTCHAN                    2324
#define IDC_TESTMIC                     2325
#define IDC_TIME1                       2326
#define IDC_TESTAMP                     2326
#define IDC_TIME2                       2327
#define IDC_TITLE                       2328
#define IDC_TONE1                       2329
#define IDC_TONE2                       2330
#define IDC_TONE4                       2331
#define IDC_TONE5                       2336
#define IDC_TOPIC                       2338
#define IDC_TREEFRAME                   2339
#define IDC_TYPE                        2340
#define IDC_UNITS                       2341
#define IDC_UOM                         2345
#define IDC_USEALL                      2347
#define IDC_USEBHIGH                    2348
#define IDC_USEBRES                     2349
#define IDC_USECALIB                    2350
#define IDC_USECHAMBER                  2351
#define IDC_USEFREQ                     2352
#define IDC_USEOHMS                     2353
#define IDC_USEPORT                     2354
#define IDC_USERNAME                    2355
#define IDC_USETIME                     2356
#define IDC_VALUE                       2357
#define IDC_VALUE2                      2358
#define IDC_VARYBY                      2359
#define IDC_VAS                         2362
#define IDC_VB                          2363
#define IDC_VB2                         2364
#define IDC_VERT1                       2365
#define IDC_VERT2                       2366
#define IDC_VERT3                       2367
#define IDC_VOLUME                      2368
#define IDC_VOLUMEAMT                   2369
#define IDC_MASS                        2369
#define IDC_VOLUNIT                     2370
#define IDC_VOLUNIT2                    2371
#define IDC_VOLUNIT3                    2372
#define IDC_WARNING                     2373
#define IDC_WATT                        2374
#define IDC_WRATE                       2376
#define IDC_XMAX                        2378
#define IDC_SENSE                       2379
#define IDC_XOVERALL                    2380
#define IDC_BL                          2381
#define IDC_XOVERTYPE                   2382
#define IDC_PE                          2383
#define IDC_XPOS1                       2384
#define IDC_YPOS                        2385
#define IDC_YPOS1                       2386
#define IDC_ZPOS                        2387
#define IDC_STATICRES                   2388
#define IDC_STATRADIUS                  2389
#define IDC_STATHEIGHT                  2390
#define IDC_STATWIDTH                   2391
#define IDC_STATLENGTH                  2392
#define IDC_TONE3                       2393
#define IDC_STATVOLUME                  2393
#define IDC_STATMASS                    2394
#define IDC_STATVAS                     2395
#define IDC_STATDIAM                    2396
#define IDC_STATMAX                     2397
#define IDC_STATOFFSET                  2399
#define IDC_CORRELATE                   2400
#define IDC_TEST2                       2402
#define IDC_TEST                        2403
#define IDC_RESIST                      2403
#define IDC_CAPACITOR                   2404
#define IDC_CUSTOM                      2405
#define IDC_KNOWN                       2408
#define IDC_MEASURED                    2409
#define IDC_MSROLD                      2410
#define IDC_REFOLD                      2411
#define IDC_REFNEW                      2412
#define IDC_SERIESNEW                   2413
#define IDC_SERIESOLD                   2414
#define IDC_SINGLECLICK                 2414
#define IDC_FILENAME                    2415
#define IDC_FILESIZE                    2416
#define IDC_FILEDATE                    2417
#define IDC_FILELAST                    2418
#define IDC_DRIVERS                     2419
#define IDC_NETWORKS                    2420
#define IDC_ENCLOSURES                  2421
#define IDC_COMMENTS                    2422
#define IDC_FOLDERSIZE                  2423
#define IDC_FOLDERNAME                  2424
#define IDC_USELAST                     2424
#define IDC_FOLDERDATE                  2425
#define IDC_DEBUGON                     2425
#define IDC_LONGSTATUS                  2425
#define IDC_FOLDERLAST                  2426
#define IDC_L1A                         2427
#define IDC_L1B                         2428
#define IDC_L2                          2430
#define IDC_C2                          2431
#define IDC_R2                          2432
#define IDC_NORECALC                    2438
#define IDC_BACKCOLOR                   2440
#define IDC_GRIDCOLOR                   2441
#define IDC_INTCOLOR                    2442
#define IDC_LATENCY                     2443
#define IDC_REPCOUNT                    2444
#define IDC_SPINCNT                     2445
#define IDC_STATMAXRATE                 2447
#define IDC_TUNING                      2449
#define IDC_NUMDRIVER                   2450
#define IDC_NUMPORT                     2451
#define IDC_MICCHANNEL                  2452
#define IDC_REFCHANNEL                  2453
#define IDC_ALLOWEDLOCALE               2453
#define IDC_TRAILS                      2454
#define IDC_LEFTMAX                     2455
#define IDC_SAVETIME                    2455
#define IDC_RIGHTMAX                    2456
#define IDC_RIGHTSHIFT                  2456
#define IDC_LEFTAVE                     2457
#define IDC_RIGHTAVE                    2458
#define IDC_LEFTMIN                     2459
#define IDC_CHECKRES                    2459
#define IDC_RIGHTMIN                    2460
#define IDC_CHECKSERIES                 2460
#define IDC_WARMUP                      2460
#define IDC_CHECKINPUTRES               2461
#define IDC_BRSTCYCLES                  2461
#define IDC_CHECKINPUTCAP               2462
#define IDC_PISTON                      2462
#define IDC_PORTAREA                    2463
#define IDC_HITPORT                     2465
#define IDC_UNITS1                      2466
#define IDC_PORTUNITS                   2466
#define IDC_SELRESIST                   2467
#define IDC_DATASET                     2468
#define IDC_STARTFREQ                   2470
#define IDC_DRAWENDS                    2471
#define IDC_PICKFNT                     2473
#define IDC_SUMMARYFONT                 2474
#define IDC_ENABLE48K                   2476
#define IDC_ENABLE96K                   2477
#define IDC_VALUENAME                   2478
#define IDC_TEXT                        2480
#define IDC_VALUELABEL                  2481
#define IDC_DRAWLINE                    2483
#define IDC_DRAWBOX                     2484
#define IDC_FILLBOX                     2485
#define IDC_SELFACE                     2487
#define IDC_FILLCOLOR                   2488
#define IDC_TYPEFACE                    2489
#define IDC_SELVALUE                    2492
#define IDC_SELTARGET                   2495
#define IDC_NUMPOINTS                   2496
#define IDC_CFRAME                      2498
#define IDC_TOVARY                      2499
#define IDC_USEENTIRE                   2500
#define IDC_RESSTATIC                   2500
#define IDC_USEMARKER                   2501
#define IDC_RESISTANCE                  2501
#define IDC_USECUSTOM                   2502
#define IDC_STDIST                      2502
#define IDC_SPECTRUM                    2503
#define IDC_AIRTEMP                     2503
#define IDC_FREQDIST                    2504
#define IDC_DISTANCE                    2504
#define IDC_POWERDIST                   2505
#define IDC_COUNTRYCODE                 2505
#define IDC_AUTOSAVE                    2506
#define IDC_MINUTE                      2507
#define IDC_STATPISTON                  2508
#define IDC_STATPORT                    2509
#define IDC_STATDRIV                    2510
#define IDC_STATOFF                     2512
#define IDC_STATNAME                    2513
#define IDC_INDIE                       2515
#define IDC_FLIP                        2516
#define IDC_OFFUNIT                     2517
#define IDC_STATDRV                     2518
#define IDC_STATPRT                     2519
#define IDC_PISTONUNITS                 2522
#define IDC_DELAYTIME                   2523
#define IDC_STDHEIGHT                   2524
#define IDC_STDWIDTH                    2525
#define IDC_STDDEPTH                    2526
#define IDC_STDVOLUME                   2527
#define IDC_RATIO                       2529
#define IDC_HEIGHT                      2530
#define IDC_WIDTH                       2531
#define IDC_DEPTH                       2532
#define IDC_USERATIO                    2533
#define IDC_SPINNUM                     2534
#define IDC_SPINPORT                    2535
#define IDC_SERIESPAR                   2536
#define IDC_SRCSELECT                   2538
#define IDC_WINDOW                      2539
#define IDC_REFSELECT                   2540
#define IDC_REFNONE                     2541
#define IDC_EDIT2                       2542
#define IDC_SPIN                        2543
#define IDC_APPLY                       2544
#define IDD_ABOUTBOX                    3000
#define IDD_ADDPASSIVE                  3001
#define IDD_CALCBANDAIR                 3002
#define IDD_CALCBANDCHAMBER             3003
#define IDD_CALCPASSIVE                 3005
#define IDD_CALCSEALED                  3006
#define IDD_CALCTUNED                   3007
#define IDD_CALCVENTED                  3008
#define IDD_CALIBRATE                   3009
#define IDD_CHDATA                      3014
#define IDD_CHGEN                       3015
#define IDD_CHGRID                      3016
#define IDD_COMPENSATION                3017
#define IDD_CROSSOPT                    3018
#define IDD_CROSSOVER                   3019
#define IDD_DRDATAS                     3020
#define IDD_DRGENERAL                   3021
#define IDD_DRPARMS                     3022
#define IDD_DRVRESTIMATE                3023
#define IDD_DSDATA                      3024
#define IDD_DSGENERAL                   3025
#define IDD_ENCLGENERAL                 3026
#define IDD_ENCLPARMS                   3027
#define IDD_GENGENERAL                  3028
#define IDD_GRPDELAY                    3029
#define IDD_LOCATIONS                   3030
#define IDD_MLS                         3031
#define IDD_MSRDISTORT                  3032
#define IDD_NETDRIVE                    3033
#define IDD_NETGENERAL                  3034
#define IDD_NETLAYOUT                   3035
#define IDD_NETLIST                     3036
#define IDD_NOISE                       3037
#define IDD_NOTCHFILTER                 3038
#define IDD_PASSIVERESULT               3039
#define IDD_PERTURB                     3040
#define IDD_PLAYSOUND                   3041
#define IDD_PREFCHART                   3042
#define IDD_PREFIMPEDANCE               3043
#define IDD_PREFMARKER                  3044
#define IDD_PREFMEASURE                 3045
#define IDD_PREFNETWORK                 3046
#define IDD_PREFREFERENCE               3047
#define IDD_PREFTRANSFORM               3048
#define IDD_PULSE                       3049
#define IDD_RECORD                      3050
#define IDD_RENAME                      3051
#define IDD_ROOMGENERAL                 3052
#define IDD_ROOMLIST                    3053
#define IDD_ROOMWALL                    3054
#define IDD_SAWTOOTH                    3055
#define IDD_SELECTOBJECT                3056
#define IDD_SINE                        3057
#define IDD_SQUARE                      3058
#define IDD_SWEEP                       3059
#define IDD_TONES                       3060
#define IDD_USERWAVE                    3061
#define IDD_WARBLE                      3062
#define IDD_XCADD                       3063
#define IDD_XCIMP                       3064
#define IDD_XFCALCFREQ                  3065
#define IDD_XFCORRELATE                 3066
#define IDD_XFDELAY                     3067
#define IDD_XFFFT                       3068
#define IDD_XFFILTER                    3069
#define IDD_XFIFFT                      3070
#define IDD_XFINVERT                    3071
#define IDD_XFLIMIT                     3072
#define IDD_XFSCALE                     3073
#define IDD_XFSMOOTH                    3074
#define IDD_XFSPLICE                    3075
#define IDD_XFTRUNCATE                  3076
#define IDD_MSRINTERMOD                 3077
#define IDD_PREFGENERAL                 3078
#define IDD_CAL_LP_BEGIN                3080
#define IDD_CAL_LP_JIG                  3081
#define IDD_CAL_LP_END                  3082
#define IDD_CAL_IMP_BEGIN               3083
#define IDD_CAL_IMP_END                 3084
#define IDD_CAL_IMP_JIG1                3085
#define IDD_CAL_IMP_JIG2                3086
#define IDD_CAL_BRD_BEGIN               3087
#define IDD_CAL_BRD_END                 3088
#define IDD_CAL_BRD_JIG                 3089
#define IDD_CAL_AMP_BEGIN               3090
#define IDD_CAL_AMP_END                 3091
#define IDD_AUDIOCHECK                  3093
#define IDD_AUDCHKOUT                   3094
#define IDD_AUDCHKIN                    3095
#define IDOP_ADDCAPACITOR               4000
#define IDOP_ADDINDUCTOR                4001
#define IDOP_ADDRESISTOR                4002
#define IDOP_CALCDRIVER                 4003
#define IDOP_CALCFREQ                   4004
#define IDOP_CALCFRESPONSE              4005
#define IDOP_CHANGE                     4006
#define IDOP_COMBINE                    4007
#define IDOP_COPY                       4009
#define IDOP_CROSSOVER                  4010
#define IDOP_CUT                        4011
#define IDOP_DELAY                      4012
#define IDOP_DELETE                     4013
#define IDOP_FFT                        4014
#define IDOP_FILTER                     4015
#define IDOP_GRPDELAY                   4016
#define IDOP_IFFT                       4017
#define IDOP_IMPEDANCE                  4018
#define IDOP_INSERT                     4019
#define IDOP_INVERT                     4020
#define IDOP_LIMIT                      4021
#define IDOP_MOVE                       4022
#define IDOP_MSRDISTORTION              4023
#define IDOP_MSRFREQUENCY               4024
#define IDOP_MSRIMPEDANCE               4025
#define IDOP_MSRINTERMOD                4026
#define IDOP_MSRMICGATED                4027
#define IDOP_MSRMICROPHONE              4028
#define IDOP_MSRPASSIVE                 4029
#define IDOP_MSRTIME                    4030
#define IDOP_MSRTRANSFER                4031
#define IDOP_NOTCH                      4032
#define IDOP_PASTE                      4033
#define IDOP_PLAY                       4034
#define IDOP_RECORD                     4035
#define IDOP_RENAME                     4036
#define IDOP_SCALE                      4037
#define IDOP_SMOOTH                     4038
#define IDOP_SPLICE                     4039
#define IDOP_TRUNCATE                   4040
#define IDOP_UNKNOWN                    4041
#define IDOP_ZOBEL                      4042
#define IDOP_CALCEQUIV                  4043
#define IDOP_MERGEPORT                  4044
#define IDOP_LPAD                       4045
#define IDOP_GOAL                       4046
#define IDOP_NETOPT                     4047
#define IDOP_MAKETEMP                   4048
#define IDOP_MAKEPERM                   4049
#define IDOP_ADDDRIVER                  4050
#define IDERR_NODRIVER                  4500
#define IDERR_NOIMPED                   4501
#define IDERR_BADFREQ                   4502
#define IDERR_NOROOT                    4503
#define IDERR_NOFREEAIR                 4504
#define IDERR_MASSBIG                   4505
#define IDERR_NOPISTON                  4506
#define IDERR_DRVCHART                  4507
#define IDERR_CANTALIGN                 4508
#define IDERR_WAVEQUERY                 4509
#define IDERR_CANTPLAYFORMAT            4510
#define IDERR_FAILOPENWAVEOUT           4511
#define IDERR_PREPAREHDR                4512
#define IDERR_FAILWRITEBLOCK            4513
#define IDERR_CANTREADFORMAT            4514
#define IDERR_FAILEDOPENINPUT           4515
#define IDERR_PREPAREINHDR              4516
#define IDERR_FAILBLOCKREAD             4517
#define IDERR_ESTIMATEBUILT             4518
#define IDERR_LOGNEGATIVE               4519
#define IDERR_FAILEDCREATEINPUT         4520
#define IDERR_FAILEDCREATEINWAVE        4521
#define IDERR_FAILADDINBUFFER           4522
#define IDERR_JIG_BACKWARDS             4523
#define IDERR_JIG_OPEN                  4524
#define IDERR_DRIVETOGND                4525
#define IDERR_NORESPONSE                4526
#define IDERR_NOIMPEDANCE               4527
#define IDERR_MULTIDRIVE                4528
#define IDERR_NOGOAL                    4529
#define IDERR_NOTEMP                    4530
#define IDERR_INVALIDENTRY              4531
#define IDERR_DRVNOIMP                  4532
#define IDERR_BADDATA                   4533
#define IDERR_NOZERO                    4534
#define IDERR_NOPEAK                    4535
#define IDERR_NORISE                    4536
#define IDERR_NOZERO2                   4537
#define IDERR_NOSTART                   4538
#define IDERR_NOTTIME                   4539
#define IDERR_TOOMUCHTIME               4540
#define IDR_AUDCHARTTYPE                5000
#define IDR_AUDDATATYPE                 5001
#define IDR_AUDDRIVETYPE                5002
#define IDR_AUDENCLTYPE                 5003
#define IDR_AUDGENTYPE                  5004
#define IDR_AUDNETTYPE                  5005
#define IDR_AUDROOMTYPE                 5006
#define IDR_AUDTESTYPE                  5007
#define IDR_AUDTESTYPE_SRVR_EMB         5008
#define IDS_STRING5008                  5008
#define IDR_AUDTESTYPE_SRVR_IP          5009
#define IDR_AUDTREETYPE                 5010
#define IDR_COMPHORZ1                   5011
#define IDR_COMPHORZ2                   5012
#define IDR_COMPHORZ3                   5013
#define IDR_COMPVERT1                   5014
#define IDR_COMPVERT2                   5015
#define IDR_COMPVERT3                   5016
#define IDR_MGENVIEW                    5019
#define IDR_MNETVIEW                    5020
#define IDR_MSUBCHARTVIEW               5021
#define IDI_AUDCHK_DUPLEX               5021
#define IDR_MTESTVIEW                   5022
#define IDI_AUDCHK_INPUT                5022
#define IDR_MTREEVIEW                   5023
#define IDI_AUDCHK_OUTPUT               5023
#define IDSUF_CALCDRIVER                6000
#define IDSUF_CALCFREQ                  6001
#define IDSUF_DISTORT                   6002
#define IDSUF_FFT                       6003
#define IDSUF_GRPDELAY                  6004
#define IDSUF_IFFT                      6005
#define IDSUF_IMPEDANCE                 6006
#define IDSUF_INTERMOD                  6007
#define IDSUF_SPLICE                    6008
#define IDS_AMPLITUDE                   6009
#define IDS_BANDAIRINFO                 6010
#define IDS_BANDPASSINFO                6011
#define IDS_CALCADDINFO                 6012
#define IDS_CALCFREQINFO                6013
#define IDS_CALCPASSINFO                6014
#define IDS_CALCTUNEDINFO               6015
#define IDS_CALIB                       6016
#define IDS_CALIBRATION                 6017
#define IDS_CHAMBER1                    6018
#define IDS_CHAMBER2                    6019
#define IDS_CHART                       6020
#define IDS_DATASET                     6021
#define IDS_DEFAULTNEW                  6022
#define IDS_DELAYINFO                   6023
#define IDS_DRIVER                      6024
#define IDS_DRIVETOAIR                  6025
#define IDS_DRIVETOCH1                  6026
#define IDS_DRVRESTIMATEINFO            6027
#define IDS_ENCLOSURE                   6028
#define IDS_ERR_SRCCHANGE               6029
#define IDS_ERR_SRCDELETE               6030
#define IDS_ERR_VALIDDATA               6031
#define IDS_F2                          6032
#define IDS_F2NEG                       6033
#define IDS_F3                          6034
#define IDS_F4                          6035
#define IDS_F5                          6036
#define IDS_FARFIELD                    6037
#define IDS_FFTINFO                     6038
#define IDS_FILTER                      6039
#define IDS_FILTERINFO                  6040
#define IDS_FNAXISSCALE                 6041
#define IDS_FNAXISTITLE                 6042
#define IDS_FNLEGEND                    6043
#define IDS_FNNETDATA                   6044
#define IDS_FNNETLABEL                  6045
#define IDS_FNSUBTITLE                  6046
#define IDS_FONTNAME                    6047
#define IDS_FREEAIR                     6048
#define IDS_FREQONAXIS                  6049
#define IDS_FREQUENCY                   6050
#define IDS_GENERATE                    6051
#define IDS_GRPDELAYINFO                6052
#define IDS_HARMON2                     6053
#define IDS_HARMON3                     6054
#define IDS_HARMON4                     6055
#define IDS_HARMON5                     6056
#define IDS_IFFTINFO                    6057
#define IDS_IMPEDANCE                   6058
#define IDS_INVERTINFO                  6059
#define IDS_KEYDISTINFO                 6060
#define IDS_LIMITINFO                   6061
#define IDS_MICGATED                    6062
#define IDS_MICRESPONSE                 6063
#define IDS_NEARFIELD                   6064
#define IDS_NETWORK                     6065
#define IDS_NEWRESOURCE                 6066
#define IDS_NODRIVER                    6067
#define IDS_NOFREQ                      6068
#define IDS_NOIMP                       6069
#define IDS_NOTCHINFO                   6070
#define IDS_PASSIVEINFO                 6071
#define IDS_PERTURBINFO                 6072
#define IDS_PHASE                       6073
#define IDS_PREFERENCE                  6074
#define IDS_PROGRECORD                  6075
#define IDS_PROJTREE                    6076
#define IDS_PULSE                       6077
#define IDS_RANGESHOW                   6078
#define IDS_RECORDINFO                  6079
#define IDS_RESCHART                    6080
#define IDS_RESDATASET                  6081
#define IDS_RESDRIVER                   6082
#define IDS_RESENCLOSURE                6083
#define IDS_RESFOLDER                   6084
#define IDS_RESNETWORK                  6085
#define IDS_RESROOM                     6086
#define IDS_RESSIGNAL                   6087
#define IDS_ROOM                        6088
#define IDS_SCALEINFO                   6089
#define IDS_SEALED                      6090
#define IDS_SEALEDINFO                  6091
#define IDS_SELECTA                     6092
#define IDS_SMOOTHINFO                  6093
#define IDS_SPLICEINFO                  6094
#define IDS_STATCALC                    6095
#define IDS_STATCALCFFT                 6096
#define IDS_STATCALCIFFT                6097
#define IDS_STATCOMBINE                 6098
#define IDS_STATCORRELATE               6099
#define IDS_STATFILTER                  6100
#define IDS_STATMEASURE                 6101
#define IDS_STATSMOOTH                  6102
#define IDS_TIME                        6103
#define IDS_TOTAL                       6104
#define IDS_TOTALFREQ                   6105
#define IDS_TRANSFER                    6106
#define IDS_TREEINFO                    6107
#define IDS_TRUNCATEINFO                6108
#define IDS_VENTEDINFO                  6109
#define IDS_XAXIS                       6110
#define IDS_XOVERINFO                   6111
#define IDS_Y2AXIS                      6112
#define IDS_YAXIS                       6113
#define IDS_ZOBELINFO                   6114
#define IDS_KEYINTERINFO                6115
#define IDR_MSUBLINEAR                  6116
#define IDS_ERR_NOZOOM                  6116
#define IDR_MSUBAREA                    6117
#define IDS_FREQ30                      6117
#define IDR_MSUBVOLUME                  6118
#define IDS_FREQ60                      6118
#define IDR_TOOLCHART                   6119
#define IDS_MSR_FORMAT                  6119
#define IDR_AUDDATATYPE1                6119
#define IDS_MSR_IMPFREE                 6120
#define IDS_MSR_IMPSEAL                 6121
#define IDS_MSR_IMP                     6122
#define IDS_MSR_FREQ                    6123
#define IDS_MSR_ONAXIS                  6124
#define IDS_MSR_FREQ30                  6125
#define IDS_MSR_FREQ60                  6126
#define IDS_MSR_MIC                     6127
#define IDS_MSR_GATED                   6128
#define IDR_TOOLSIGNAL                  6129
#define IDS_MSR_PULSE                   6129
#define IDS_MSR_NEAR                    6130
#define IDR_TOOLDRIVER                  6131
#define IDS_MSR_FAR                     6131
#define IDS_MSR_XFER                    6132
#define IDR_TOOLNETWORK                 6133
#define IDS_MSR_RESPONSE                6133
#define IDS_MSR_TIME                    6134
#define IDR_TOOLENCL                    6135
#define IDS_MAKECHART                   6135
#define IDS_FFTDESC                     6136
#define IDB_WIZ_IMP_BEGIN               6137
#define IDS_IFFTDESC                    6137
#define IDB_WIZ_IMP_JIG1                6138
#define IDS_GRPDDESC                    6138
#define IDB_WIZ_IMP_JIG2                6139
#define IDS_FREQRESPDESC                6139
#define IDS_IMPEDDESC                   6140
#define IDB_WIZ_LP_BEGIN                6141
#define IDS_COMBINEDESC                 6141
#define IDB_WIZ_BRD_BEGIN               6142
#define IDS_SPLICEDESC                  6142
#define IDB_WIZ_BRD_JIG                 6143
#define IDS_LOCATIONTOP                 6143
#define IDB_WIZ_LP_JIG                  6144
#define IDS_READONLY                    6144
#define IDB_WIZ_AMP_BEGIN               6145
#define IDD_CAL_IMP_LIST                6145
#define IDS_SYSTEM                      6145
#define IDB_RESISTOR                    6146
#define IDS_ISROOT                      6146
#define IDD_ROOTVIEW                    6147
#define IDS_DOCUMENT                    6147
#define IDB_WIZ_VOL_BEGIN               6147
#define IDD_DOCGENERAL                  6148
#define IDS_FOLDER                      6148
#define IDD_CAL_VOL_BEGIN               6149
#define IDS_ADDEDMASS                   6149
#define IDD_CAL_VOL_END                 6150
#define IDS_MSR_IMPMASS                 6150
#define IDS_ERR_SEALED                  6151
#define IDD_PREFDEBUG                   6151
#define IDS_ERR_MASS                    6152
#define IDD_DRVEQUIV                    6152
#define IDS_ERR_NOVAS                   6153
#define IDD_FLDGENERAL                  6153
#define IDS_CHARTTITLE                  6154
#define IDD_PREFACOUSTIC                6154
#define IDS_CHARTSCALE                  6155
#define IDD_VUMETER                     6155
#define IDS_CHARTLEGEND                 6156
#define IDD_WARNDEFAULT                 6156
#define IDS_CHARTSUBTITLE               6157
#define IDD_BURST                       6157
#define IDS_CHARTAXISTITLE              6158
#define IDD_CALCMERGE                   6158
#define IDS_CHARTDEF                    6159
#define IDD_LPAD                        6159
#define IDS_NETDATA                     6160
#define IDD_DISABLE48K                  6160
#define IDS_NETLEGEND                   6161
#define IDD_ANNOTATE                    6161
#define IDS_SYSDESCRIPT                 6162
#define IDD_CREATEGOAL                  6162
#define IDS_ACOUSTICINFO                6163
#define IDD_NETOPTIMIZE                 6163
#define IDS_DESCGATE                    6164
#define IDD_TIMEDIST                    6164
#define IDC_UNITER                      6164
#define IDS_DEFCHARTFREQ                6165
#define IDD_ADDDRIVER                   6165
#define IDS_DEFCHARTTIME                6166
#define IDD_VOLUMECALC                  6166
#define IDS_DEFCHARTOHM                 6167
#define IDD_XFWATERFALL                 6167
#define IDS_UNDERCONSTRUCT              6168
#define IDD_CHARTPROP                   6168
#define IDS_DESCSTARTGATE               6169
#define IDD_NETBAR                      6169
#define IDS_LPADINFO                    6170
#define IDS_SUMMARY                     6171
#define IDS_NOTEINFO                    6172
#define IDS_NOTEFONT                    6173
#define IDS_GOALINFO                    6174
#define IDSUF_GOAL                      6175
#define IDS_OPTIMINFO                   6176
#define IDS_TIMEDISTINFO                6177
#define IDS_GATEFREQ                    6178
#define IDS_MSR_GATEFREQ                6179
#define IDS_MSR_PORTFREQ                6180
#define IDS_PORTFREQ                    6181
#define IDS_VOLCALCINFO                 6182
#define IDS_MAKEWATER                   6183
#define IDS_WATERTITLE                  6184
#define IDINDIC_AMPLITUDE               6200
#define IDINDIC_PHASE                   6201
#define IDINDIC_VALUE                   6202
#define IDINDIC_RESIST                  6203
#define IDINDIC_FREQ                    6204
#define IDINDIC_POSTPHASE               6205
#define IDINDIC_POSTVALUE               6206
#define IDSCH_FREQUENCY                 6207
#define IDSCH_TIME                      6208
#define IDSCH_IMPEDANCE                 6209
#define IDSCH_AMPLITUDE                 6210
#define IDSCH_PHASE                     6211
#define IDSCH_AMPDB                     6212
#define IDSUF_MERGE                     6213
#define IDSCH_KFREQUENCY                6214
#define IDS_DRV_RESONANT_FREQ           7000
#define IDS_DRV_INDUCTANCE              7001
#define IDS_DRV_QMS                     7002
#define IDS_DRV_QES                     7003
#define IDS_DRV_TOTALQ                  7004
#define IDS_DRV_VAS                     7005
#define IDS_DRV_PISTON                  7006
#define IDS_DRV_XMAX                    7007
#define IDS_DRV_SENSITIVITY             7008
#define IDS_DRV_VOL                     7009
#define IDS_DRV_MASS                    7010
#define IDS_DRV_RE                      7011
#define IDS_DRV_USERRE                  7012
#define IDS_DRV_USEADDED                7013
#define IDS_DRV_BL                      7014
#define IDS_DRV_PE                      7015
#define IDS_DRV_NAME                    7016
#define IDS_DRVS_RESONANT_FREQ          7017
#define IDS_DRVS_INDUCTANCE             7018
#define IDS_DRVS_QMS                    7019
#define IDS_DRVS_QES                    7020
#define IDS_DRVS_TOTALQ                 7021
#define IDS_DRVS_VAS                    7022
#define IDS_DRVS_PISTON                 7023
#define IDS_DRVS_XMAX                   7024
#define IDS_DRVS_SENSITIVITY            7025
#define IDS_DRVS_VOL                    7026
#define IDS_DRVS_MASS                   7027
#define IDS_DRVS_RE                     7028
#define IDS_DRVS_USERRE                 7029
#define IDS_DRVS_USEADDED               7030
#define IDS_DRVS_BL                     7031
#define IDS_DRVS_PE                     7032
#define IDS_DRVS_NAME                   7033
#define IDS_DRV_IND2                    7033
#define IDS_DRVS_IND2                   7034
#define IDS_DRV_R1                      7035
#define IDS_DRVS_R1                     7036
#define IDS_DRV_DESCRIPT                7037
#define IDS_DRVS_NULL                   7039
#define IDS_ENC_NAME                    7100
#define IDS_FRM_NULL                    7101
#define IDS_ENC_DESCRIPT                7102
#define IDS_ENC_DRIVER                  7103
#define IDS_ENC_VOL                     7104
#define IDS_FRM_LITER                   7105
#define IDS_ENC_QLEAK                   7106
#define IDS_ENC_QDAMP                   7107
#define IDS_ENC_QPORT                   7108
#define IDS_ENC_USEPORT                 7109
#define IDS_ENC_PLENGTH                 7110
#define IDS_FRM_CM                      7111
#define IDS_ENC_PRADIUS                 7112
#define IDS_ENC_PWIDTH                  7113
#define IDS_ENC_PHEIGHT                 7114
#define IDS_ENC_USECHAMBER              7115
#define IDS_ENC_DRIVERS                 7116
#define IDS_ENC_PARALLEL                7117
#define IDS_ENC_DRVRES                  7118
#define IDS_FRM_OHMS                    7119
#define IDS_ENC_ISCIRCULAR              7120
#define IDS_FRM_SQIN                    7121
#define IDS_FRM_INCH                    7122
#define IDS_FRM_OZ                      7123
#define IDS_FRM_CUFT                    7124
#define IDS_DSDATA_UOM                  8000
#define IDS_DSDATA_DOM                  8001
#define IDS_XCADD_OPERATION             8002
#define IDS_NETLIST_COMPTYPE            8003
#define IDS_GENGENERAL_TYPE             8004
#define IDS_GENGENERAL_RATE             8005
#define IDS_RECORD_OUTPUT               8006
#define IDS_RECORD_CALIB                8007
#define IDS_RECORD_DATA                 8008
#define IDS_PREFT_FFTWINDOW             8009
#define IDS_PLAYS_OUTPUT                8010
#define IDS_ADDP_COMPTYPE               8011
#define IDS_PASS_COMBTYPE               8012
#define IDS_CALCS_ALIGNMENT             8013
#define IDS_CALCV_ALIGNMENT             8014
#define IDS_XFFILTER_FTYPE              8015
#define IDS_XFFILTER_FSHAPE             8016
#define IDS_XFSMOOTH_METHOD             8017
#define IDS_XFFFT_FFTWINDOW             8018
#define IDS_CROSS_ORDER                 8019
#define IDS_CROSS_HIGHLOW               8020
#define IDS_COMPEN_TYPE                 8021
#define IDS_PREFN_DIGITS                8022
#define IDS_PREFN_RESTYPE               8023
#define IDS_XFCF_FFTWINDOW              8024
#define IDS_XFCF_CALIB                  8025
#define IDS_XFSCALE_METHOD              8026
#define IDS_PREFG_UNITS                 8027
#define IDS_PREFA_MIC                   8028
#define IDS_PREFA_REF                   8029
#define IDS_GOAL_ORDER                  8030
#define IDS_GOAL_HIGHLOW                8031
#define IDS_GOAL_XOVERALL               8032
#define IDS_CROSS_XOVERALL              8033
#define IDS_MENU_MAKETEMP               8034
#define IDS_MENU_MAKEPERM               8035
#define IDS_IMPORT                      8036
#define IDS_EXPORT                      8037
#define IDS_SAVEREGISTRY                8038
#define IDS_FULLCOMP                    8039
#define IDS_PARTIALCOMP                 8040
#define IDS_NOTCOMP                     8041
#define IDS_DUPFULL                     8042
#define IDS_DUPNOT                      8043
#define IDS_CHK_USEFULL                 8044
#define IDS_CHK_PLAYLOW                 8045
#define IDS_CHK_RECLOW                  8046
#define IDS_CHK_USELOW                  8047
#define IDS_CHK_NOREC                   8048
#define IDS_CHK_NOLOW                   8049
#define IDS_CHK_NOUSE                   8050
#define IDS_CHK_LRVOLUME                8051
#define IDS_CHK_PITCH                   8052
#define IDS_CHK_PLAYBACKRATE            8053
#define IDS_CHK_SYNC                    8054
#define IDS_CHK_VOLUME                  8055
#define IDS_CHK_SAMPLEACCURATE          8056
#define IDS_STEREO                      8057
#define IDS_MONO                        8058
#define IDS_UNKNOWN                     8059
#define IDS_CHK_FORMAT                  8060
#define IDS_UNIT_IN                     8061
#define IDS_UNIT_FT                     8062
#define IDS_UNIT_MM                     8063
#define IDS_UNIT_CM                     8064
#define IDS_UNIT_IN3                    8065
#define IDS_UNIT_FT3                    8066
#define IDS_UNIT_MM3                    8067
#define IDS_UNIT_CM3                    8068
#define IDS_UNIT_LITERS                 8069
#define IDS_UNIT_M3                     8070
#define IDS_UNIT_IN2                    8071
#define IDS_UNIT_FT2                    8072
#define IDS_UNIT_MM2                    8073
#define IDS_UNIT_CM2                    8074
#define IDS_UNIT_M2                     8075
#define IDS_UNIT_GM                     8076
#define IDS_UNIT_KG                     8077
#define IDS_UNIT_OZ                     8078
#define IDS_UNIT_LB                     8079
#define IDS_UNIT_DEGF                   8080
#define IDS_UNIT_DEGC                   8081
#define IDS_UNIT_M                      8082
#define IDS_YES                         8083
#define IDS_NO                          8084
#define IDS_IMPORTED                    8085
#define IDS_VUMETERTOP                  8086
#define IDS_OHM                         8087
#define IDS_FARAD                       8088
#define IDS_HENRY                       8089
#define IDS_VOLT                        8090
#define IDS_HERTZ                       8091
#define IDS_DB                          8092
#define IDS_MSEC                        8093
#define IDS_DEGREE                      8094
#define IDS_NEWITEM                     8095
#define IDS_SOURCE                      8096
#define IDS_DRIVERINFO                  8097
#define IDS_MHENRY                      8098
#define IDS_UFARAD                      8099
#define IDS_SERIESPAR                   8100
#define IDS_WATERINFO                   8101
#define IDS_MERGEDESC                   8102
#define IDP_OLE_INIT_FAILED             12043
#define ID_CALCULATE_COMBINE            32773
#define ID_CALCULATE_CONEEXCURSION      32774
#define ID_CALCULATE_DRIVERPARAMETERS   32776
#define ID_CALCULATE_FFT                32777
#define ID_CALCULATE_FREQUENCY          32778
#define ID_CALCULATE_FREQUENCYRESPONSE  32779
#define ID_CALCULATE_GROUPDELAY         32780
#define ID_CALCULATE_IFFT               32781
#define ID_CALCULATE_IMPEDANCE          32782
#define ID_CALCULATE_PERTURB            32785
#define ID_CALCULATE_SPLICE             32788
#define ID_CALCULATE_TRANSIENTRESPONSE  32791
#define ID_CALC_BANDAIR                 32792
#define ID_CALC_BANDCHAMBER             32793
#define ID_CALC_SEALED                  32795
#define ID_CALC_VENTED                  32796
#define ID_CANCEL_EDIT_SRVR             32797
#define ID_CHART_ADDDATA                32798
#define ID_TRANSFORM_CHART              32800
#define ID_EDIT_CHARTPROPERTIES         32801
#define ID_EDIT_DELETE                  32802
#define ID_EDIT_INSERT                  32804
#define ID_EDIT_PROPERTIES              32805
#define ID_MEASURE_DISTORTION           32809
#define ID_MEASURE_FARFIELD             32810
#define ID_MEASURE_FREEAIR              32812
#define ID_MEASURE_FREQUENCYRESPONSE    32813
#define ID_MEASURE_GATED                32816
#define ID_MEASURE_IMPEDANCE            32817
#define ID_MEASURE_INTERMODULATIONDISTORTION 32820
#define ID_MEASURE_MICROPHONERESPONSE   32821
#define ID_MEASURE_NEARFIELD            32822
#define ID_MEASURE_PASSIVECOMPONENT     32823
#define ID_MEASURE_PULSERESPONSE        32824
#define ID_MEASURE_SEALED               32825
#define ID_MEASURE_TIMERESPONSE         32828
#define ID_MSR_FREQ_30                  32831
#define ID_MSR_FREQ_60                  32839
#define ID_MSR_FREQ_ONAXIS              32840
#define ID_NETWORK_ADD_CAPACITOR        32841
#define ID_NETWORK_ADD_INDUCTOR         32842
#define ID_NETWORK_ADD_RESISTOR         32843
#define ID_NETWORK_CHANGE               32844
#define ID_NETWORK_COMPENSATION         32845
#define ID_NETWORK_STOCK                32850
#define ID_OPTIONS_CALIBRATE            32854
#define ID_OPTIONS_PASSIVE              32855
#define ID_OPTIONS_PREFERENCES          32856
#define ID_OPTIONS_TUNED                32857
#define ID_RESOURCE_EXPORT              32858
#define ID_RESOURCE_IMPORT              32859
#define ID_RESOURCE_NEW_CHART           32860
#define ID_RESOURCE_NEW_DATASET         32861
#define ID_RESOURCE_NEW_DRIVER          32862
#define ID_RESOURCE_NEW_ENCLOSURE       32863
#define ID_RESOURCE_NEW_FOLDER          32887
#define ID_RESOURCE_NEW_NETWORK         32888
#define ID_RESOURCE_NEW_ROOM            32889
#define ID_RESOURCE_NEW_SIGNAL          32891
#define ID_RESOURCE_OPEN                32892
#define ID_RESOURCE_RENAME              32893
#define ID_SHOW_BOTHINPUT               32894
#define ID_SHOW_LEFTINPUT               32895
#define ID_SHOW_OUTPUT                  32896
#define ID_SHOW_RIGHTINPUT              32897
#define ID_SOUND_CONVERTTODATA          32898
#define ID_SOUND_LOOP                   32899
#define ID_SOUND_LOOPRECORD             32900
#define ID_SOUND_PLAY                   32901
#define ID_SOUND_PLAYAGAIN              32902
#define ID_SOUND_RECORD                 32904
#define ID_SOUND_RECORDAGAIN            32905
#define ID_SOUND_STOP                   32906
#define ID_TRANSFORM_DELAY              32908
#define ID_TRANSFORM_FILTER             32913
#define ID_TRANSFORM_INVERT             32915
#define ID_TRANSFORM_LIMIT              32916
#define ID_TRANSFORM_SCALE              32917
#define ID_TRANSFORM_SMOOTH             32918
#define ID_TRANSFORM_TRUNCATE           32920
#define ID_VIEW_ZOOM                    32923
#define ID_VIEW_ZOOMOUT                 32924
#define ID_VIEW_ZOOMALL                 32925
#define ID_LIN_MM                       32926
#define ID_LIN_CM                       32927
#define ID_LIN_METER                    32928
#define ID_LIN_INCHES                   32929
#define ID_LIN_FEET                     32930
#define ID_AREA_MM                      32931
#define ID_AREA_CM                      32932
#define ID_AREA_METERS                  32933
#define ID_AREA_INCHES                  32934
#define ID_AREA_FEET                    32935
#define ID_VOL_MM                       32936
#define ID_VOL_CM                       32937
#define ID_VOL_LITRES                   32938
#define ID_VOL_METERS                   32939
#define ID_VOL_INCHES                   32940
#define ID_VOL_FEET                     32941
#define CG_ID_VIEW_TREE                 32942
#define CG_ID_VIEW_LOCATIONS            32943
#define CG_ID_VIEW_VUMETER              32944
#define ID_VIEW_RESOURCEBAR             32954
#define ID_OPTIONS_WIZARD_CHECKSOUNDCARD 32955
#define ID_WIZARD_CHECKSOUNDCARD        32956
#define ID_GEN_MEASURE_IMPEDANCE        32958
#define ID_WIZARD_SETVOLUME             32959
#define ID_MEASURE_MASS                 32960
#define ID_DRIVER_SETEQUIVALENCE        32962
#define ID_EDIT_CHARTDEFAULT            32964
#define ID_EDIT_USEDEFAULT              32966
#define ID_CALC_CORRELATE               32974
#define ID_VIEW_VUMETER                 32975
#define ID_CALC_MERGE                   32976
#define ID_NETWORK_GRID_OFF             32978
#define ID_NETWORK_GRID_2X2             32979
#define ID_NETWORK_GRID_4X4             32980
#define ID_NETWORK_GRID_8X8             32981
#define ID_NETWORK_LPAD                 32982
#define ID_CHART_ADDNOTE                32984
#define ID_CHART_NOTE                   32985
#define ID_NETWORK_CREATEGOAL           32987
#define ID_NETWORK_OPTIMIZE             32988
#define ID_OPTIONS_CALCULATOR_DISTANCE  32989
#define ID_OPTIONS_DISTANCE             32990
#define ID_OPTIONS_SAVEREGISTRY         32991
#define ID_EDIT_TEMP                    32993
#define ID_NETWORK_ADD_DRIVER           32994
#define ID_MEASURE_PORT                 32995
#define ID_MEASURE_GATEFREQ             32996
#define ID_OPTIONS_VOLUME               32999
#define ID_CALCULATE_WATERFALL          33000
#define ID_VIEW_RESOURCEDLG             33001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        6170
#define _APS_NEXT_COMMAND_VALUE         33002
#define _APS_NEXT_CONTROL_VALUE         2545
#define _APS_NEXT_SYMED_VALUE           8000
#endif
#endif
